### ISSUE TITLE
[Suggestions]D-Adaptation for Adan(Adaptive Nesterov Momentum Algorithm)

### ISSUE THREAD

**Issue by qwopqwop200** [facebookresearch/dadaptation#14]
Hi, thanks for your excellent works.
[Adan](https://arxiv.org/abs/2208.06677) is currently a SOTA optimizer.And I think that applying D-Adaptation to Adan would be very practical. So I implemented this. [D-Adaptation Adan](https://github.com/qwopqwop200/D-Adaptation-Adan/blob/main/opt/dadapt_adan.py), [D-Adaptation Adan IP](https://github.com/qwopqwop200/D-Adaptation-Adan/blob/main/opt/dadapt_adan_ip.py)
However, I'm not sure if this implementation is correct. It works very well, at least on cifar 10. It also shows higher performance than D-Adaptation Adam.
![217195448-7202126f-6682-4fb0-9c99-432f534a9c9c](https://user-images.githubusercontent.com/64115820/217252513-6a171b8a-c9b2-43c4-a3d9-01137c954bcf.png)

pseudo code

<img width="485" alt="217242205-efcb5d6e-9123-4ce4-bf31-3ffcefb002b2" src="https://user-images.githubusercontent.com/64115820/217255104-a163d87a-007d-47d5-8e56-e65b5cd73ae5.png">
where λ is the weight decay constant.

Please let me know if there are any mistakes.

**Comment by adefazio** [comment]
Hi, I will run some experiments on this and see how it goes. If you provide a pull request I will be able to merge it in if the experiments show promise.
