### ISSUE TITLE
Any chance TF version will be realeased?

### ISSUE THREAD

**Issue by georgeYanch** [facebookresearch/dadaptation#17]
Great work!

Looking forward to try tensorflow implementation is there will be any

**Comment by adefazio** [comment]
I don't have any plans to actively work on it over the next few months, sorry! I can link to any third-party implementations from the docs if anybody else implements it.

**Comment by lu-minous** [comment]
> Great work!
> 
> Looking forward to try tensorflow implementation is there will be any

May I ask if you have implemented Dadaptation in TensorFlow?
Or have you found someone else's implementation?

**Comment by adefazio** [comment]
I'm not aware of an implementation yet.
