### ISSUE TITLE
First inequality on page 3 derivation?

### ISSUE THREAD

**Issue by mega-optimus** [facebookresearch/dadaptation#18]
Hi!

I have question about the first inequality on page 3, which is critical because it produces lower bound of D.

It reads like this: `sum(dk(f(xk) - f*)) <= D||sn+1|| + sum((rk/2)dk2||gk||2) - (rn+1/2)||sn+1||2`

How is it derived? Or any reference that derives it? 

Thank you very much !

**Comment by adefazio** [comment]
This bound is proved as Lemma 5 in the Appendix A, page 19 of the PDF. If you have any questions about the proof, please feel free to ask.

**Comment by mega-optimus** [comment]
> This bound is proved as Lemma 5 in the Appendix A, page 19 of the PDF. If you have any questions about the proof, please feel free to ask.

The proof is well written, thanks!
