### ISSUE TITLE
Pip package or official PyTorch integration?

### ISSUE THREAD

**Issue by TKassis** [facebookresearch/dadaptation#2]
These sets of optimizer implementations seem promising. Is it worth packaging them as an installable pip package or better yet contributing them to the official PyTorch library?

**Comment by adefazio** [comment]
I'm going to work on packaging them this week. The official PyTorch repo recommends 50 citations before they will consider merging in a new optimizer so I can't do that yet.

**Comment by TKassis** [comment]
Sounds great! Great work by the way!
