### ISSUE TITLE
Steps per Epoc in Sample images?

### ISSUE THREAD

**Issue by DarksealStudios** [facebookresearch/dadaptation#25]
How many Steps per epoc were in the sample images found here: https://github.com/facebookresearch/dadaptation
How many steps in 1 epoc in the Epocs? Would just like to know for consistency. Apples to Apples instead of Apples to Applesauce.

**Comment by adefazio** [comment]
The batch sized used for each problem can be found in the tables in the appendix of our arxiv preprint. You should be able to convert to samples per epoch for each problem.

**Comment by DarksealStudios** [comment]
Awesome! Now, if only this made sense to the average user! I dont see how many images were used, how many samples per epoc.
![image](https://github.com/facebookresearch/dadaptation/assets/37822253/81c864d9-2955-4bfe-913a-5feebc51e559) can you translate that for the lay person? How many steps per epoc is that?

**Comment by DarksealStudios** [comment]
can you translate that for the lay person? How many steps per epoc is that?

**Comment by adefazio** [comment]
I've went through the log files to double check. The numbers are as follows: 
For IWSLT14: 1101, for GPT 62820, for Bert 3935, for DLRM 3061, For MRI 4343, for COCO 7329, for CIFAR-10 390, for CIFAR-100 781 and for ImageNet 5005.

**Comment by DarksealStudios** [comment]
> I've went through the log files to double check. The numbers are as follows: For IWSLT14: 1101, for GPT 62820, for Bert 3935, for DLRM 3061, For MRI 4343, for COCO 7329, for CIFAR-10 390, for CIFAR-100 781 and for ImageNet 5005.

 Steps per epoc?? Why so wild? Why not conform to as close to 1000 steps per epoc? Everyone is doing it, it's no big deal. Standardization would help us mere humans understand!!

**Comment by DarksealStudios** [comment]
Ty for the information.
