### ISSUE TITLE
Small mistakes in DAdaptLion class

### ISSUE THREAD

**Issue by pamparamm** [facebookresearch/dadaptation#33]
Hello! I think there is a mistake in `DAdaptLion`'s Docstring: it says "Implements Adam" instead of something like "Implements Lion", the same is for `DAdaptSGD`.
There is also an unnecessary `print("Initializing")` call in `DAdaptLion.step` function.

**Comment by adefazio** [comment]
Thank you for spotting this! I will fix it now.
