### ISSUE TITLE
No easy way to read the `dlr` during the training

### ISSUE THREAD

**Issue by mitalbert** [facebookresearch/dadaptation#37]
Hi and thanks for another great open source project.

Is there a specific reason why `dlr` and other calculated parameters should not be read during the training? I had to set up logging and a handler to see those values in my experiments.

**Comment by adefazio** [comment]
I'm happy to add some ways to read the value during training. I'm currently considering adding tensorboard and wandb logging of the values, are there any other ways of exposing the values that would be useful to you?

**Comment by mitalbert** [comment]
logging is certainly useful, and of course it's up to you, but I was thinking more like `optimizer.param_groups[0]['dlr']` just like torch does it.

**Comment by adefazio** [comment]
Accessing group['d']*group['lr'] is not so complex, so I'm inclined to leave this for now, until I incorporate more flexible logging.
