### ISSUE TITLE
TypeError: DAdaptLion.__init__() got an unexpected keyword argument 'decouple'

### ISSUE THREAD

**Issue by DarkAlchy** [facebookresearch/dadaptation#41]
What arguments should I use with this as I am currently trying to use "decouple=True weight_decay=0.6 betas=0.9,0.99 use_bias_correction=True growth_rate=1.02"?

**Comment by adefazio** [comment]
For the Lion implementation, it only supports decoupled weight decay, so there is no need to specify decouple=True.  You should also leave out use_bias_correction and growth_rate, they are also not needed for Lion.

**Comment by DarkAlchy** [comment]
Ahhh, thank you.
