### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by stefanwezel** [facebookresearch/dadaptation#8]
After installing the `pip` package and trying `import dadaptation`, I run into:

```
  File "/home/*****/anaconda3/lib/python3.9/site-packages/dadaptation/__init__.py", line 3, in <module>
    from .dadapt_sgd import DadaptSGD
ImportError: cannot import name 'DadaptSGD' from 'dadaptation.dadapt_sgd' (/home/*****/anaconda3/lib/python3.9/site-packages/dadaptation/dadapt_sgd.py)
```
Might the cause be the relative paths in `dadaption/dadaption/__init__.py`? :thinking:

**Comment by ksadov** [comment]
Had the same problem. Downgrading the package to version 1.3 fixed it in the immediate term, but it would be nice to have it fixed.

**Comment by ksadov** [comment]
Looks like it was introduced during a round of renaming in #7

**Comment by adefazio** [comment]
This should be fixed now, please let me know if it's not working for you. I pushed v1.5 with the fix.
